#!/bin/bash
#
# WARNING: this script will destroy data on the selected disk.
#
# This script can be run by executing the following:
#   curl -sL https://goo.gl/HtC7Mf | bash -s bootstrap
#

set -eoux pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=AT&country=BE&country=DK&country=FR&country=DE&country=NL&country=SE&country=CH&protocol=https&use_mirror_status=on"
PACKAGE_LIST=(
  a52dec \
  aalib \
  accountsservice \
  acl \
  acpi \
  acpi_call \
  acpid \
  acpilight \
  adobe-source-code-pro-fonts \
  adobe-source-sans-fonts \
  adwaita-icon-theme \
  aerc \
  alacritty \
  alsa-card-profiles \
  alsa-lib \
  alsa-plugins \
  alsa-topology-conf \
  alsa-ucm-conf \
  amtk \
  anki \
  ansible \
  ansible-core \
  aom \
  apache \
  apr \
  apr-util \
  arandr \
  arch-audit \
  archlinux-keyring \
  argon2 \
  aribb24 \
  aspell \
  aspell-en \
  at-spi2-atk \
  at-spi2-core \
  atk \
  atkmm \
  attr \
  audit \
  auracle-git \
  aurvote \
  autoconf \
  automake \
  autorandr \
  avahi \
  babl \
  base \
  bash \
  bat \
  bc \
  bcg729 \
  bdf-unifont \
  bind \
  binutils \
  bison \
  blas \
  blueman \
  bluez \
  bluez-libs \
  bolt \
  boomaga-qt5 \
  boost-libs \
  bottom \
  box2d \
  bridge-utils \
  broot \
  brotli \
  btrfs-progs \
  bubblewrap \
  bzip2 \
  c-ares \
  ca-certificates \
  ca-certificates-mozilla \
  ca-certificates-utils \
  cairo \
  cairomm \
  cantarell-fonts \
  cbatticon \
  cblas \
  cdparanoia \
  celt \
  cfitsio \
  cheese \
  chromaprint \
  chromium \
  cifs-utils \
  clucene \
  clutter \
  clutter-gst \
  clutter-gtk \
  cmake \
  code \
  cogl \
  colord \
  colord-gtk \
  colord-sane \
  confuse \
  containerd \
  coreutils \
  cracklib \
  cryptsetup \
  cups \
  cups-filters \
  cups-pk-helper \
  curl \
  curlie \
  darktable \
  dav1d \
  db \
  dbus \
  dbus-glib \
  dbus-python \
  dconf \
  desktop-file-utils \
  device-mapper \
  diffuse \
  diffutils \
  dina-font \
  djvulibre \
  dkms \
  dmenu \
  dmraid \
  dnssec-anchors \
  docbook-xml \
  docbook-xsl \
  docker \
  docker-compose \
  dog \
  dosfstools \
  double-conversion \
  dropbox \
  dunst \
  dust \
  e2fsprogs \
  efibootmgr \
  efivar \
  electron \
  electron11 \
  electron12 \
  electrum \
  elfutils \
  elinks \
  enblend-enfuse \
  enca \
  enchant \
  eog \
  evemu \
  evince \
  evtest \
  exa \
  exempi \
  exiv2 \
  expac \
  expat \
  faac \
  faad2 \
  fakeroot \
  fasd \
  feh \
  ffmpeg \
  ffmpegthumbnailer \
  fftw \
  figlet \
  file \
  file-roller \
  filesystem \
  findutils \
  firefox \
  flac \
  flameshot \
  flex \
  flickcurl \
  fluidsynth \
  font-bh-ttf \
  fontconfig \
  foomatic-db-engine \
  freetype2 \
  frei0r-plugins \
  fribidi \
  fuse-common \
  fuse3 \
  fzf \
  galculator \
  gavl \
  gawk \
  gc \
  gcc \
  gcc-libs \
  gcr \
  gd \
  gdbm \
  gdk-pixbuf2 \
  gdm \
  gedit \
  geeqie \
  gegl \
  gendesk \
  geoclue \
  geocode-glib \
  geteltorito \
  gettext \
  ghostscript \
  ghostwriter \
  giflib \
  gimp \
  git \
  git-crypt \
  git-delta \
  gjs \
  glew \
  glib-networking \
  glib2 \
  glibc \
  glibmm \
  glslang \
  glu \
  gmic \
  gmime3 \
  gmp \
  gnome-autoar \
  gnome-bluetooth \
  gnome-calculator \
  gnome-color-manager \
  gnome-control-center \
  gnome-desktop \
  gnome-disk-utility \
  gnome-font-viewer \
  gnome-keyring \
  gnome-online-accounts \
  gnome-screenshot \
  gnome-session \
  gnome-settings-daemon \
  gnome-shell \
  gnome-system-monitor \
  gnome-terminal \
  gnome-themes-extra \
  gnome-user-docs \
  gnome-user-share \
  gnome-video-effects \
  gnu-free-fonts \
  gnu-netcat \
  gnupg \
  gnutls \
  go \
  gobject-introspection-runtime \
  gom \
  gopass \
  gparted \
  gpg-crypter \
  gpgme \
  gpicview \
  gpm \
  gptfdisk \
  graphene \
  graphicsmagick \
  graphite \
  graphviz \
  green-recorder \
  grep \
  grilo \
  grilo-plugins \
  groff \
  gsettings-desktop-schemas \
  gsfonts \
  gsl \
  gsm \
  gsound \
  gspell \
  gssdp \
  gst-plugin-gtk \
  gst-plugin-pipewire \
  gst-plugins-bad \
  gst-plugins-bad-libs \
  gst-plugins-base \
  gst-plugins-base-libs \
  gst-plugins-good \
  gstreamer \
  gtest \
  gtk-sharp-2 \
  gtk-update-icon-cache \
  gtk-vnc \
  gtk2 \
  gtk3 \
  gtk4 \
  gtkmm3 \
  gtksourceview4 \
  gts \
  gucharmap \
  guile \
  gunicorn \
  gupnp \
  gupnp-dlna \
  gupnp-igd \
  gvfs \
  gvfs-afc \
  gvfs-goa \
  gvfs-google \
  gvfs-gphoto2 \
  gvfs-mtp \
  gvfs-nfs \
  gvfs-smb \
  gzip \
  harfbuzz \
  harfbuzz-icu \
  hdf5 \
  hdparm \
  hexchat \
  hicolor-icon-theme \
  hidapi \
  hplip \
  htop \
  http-parser \
  hugin \
  hunspell \
  hwids \
  hwloc \
  hyphen \
  i3-wm \
  i3lock-color \
  i3status \
  iana-etc \
  ibus \
  icu \
  ijs \
  imagemagick \
  imath \
  imlib2 \
  inetutils \
  intel-ucode \
  intellij-idea-community-edition \
  inter-font \
  intltool \
  iproute2 \
  iptables \
  iputils \
  iso-codes \
  ispell \
  itstool \
  iw \
  jack2 \
  jansson \
  jasper \
  java-environment-common \
  java-openjfx \
  java-runtime-common \
  java11-openjfx \
  jbig2dec \
  jdk11-openjdk \
  jdk8-openjdk \
  jemalloc \
  jfsutils \
  jpdftweak \
  jq \
  jre-openjdk \
  jre-openjdk-headless \
  jre11-openjdk \
  jre11-openjdk-headless \
  jre8-openjdk \
  jre8-openjdk-headless \
  js68 \
  js78 \
  json-c \
  json-glib \
  jsoncpp \
  kbd \
  kbdlight \
  keepassxc \
  keyutils \
  kitty \
  kitty-terminfo \
  kmod \
  krb5 \
  kwayland \
  kyotocabinet \
  l-smash \
  lame \
  lapack \
  lcms2 \
  ldb \
  ldns \
  ledger-live-bin \
  ledger-udev \
  lensfun \
  less \
  libabw \
  libaec \
  libaio \
  libao \
  libappindicator-gtk3 \
  libarchive \
  libass \
  libassuan \
  libasyncns \
  libatasmart \
  libatomic_ops \
  libavc1394 \
  libavif \
  libavtp \
  libblockdev \
  libbluray \
  libbs2b \
  libbsd \
  libbytesize \
  libcaca \
  libcanberra \
  libcap \
  libcap-ng \
  libcddb \
  libcdio \
  libcdio-paranoia \
  libcdr \
  libchamplain \
  libcloudproviders \
  libcmis \
  libcolord \
  libconfig \
  libcroco \
  libcue \
  libcups \
  libdaemon \
  libdatrie \
  libdbusmenu-glib \
  libdbusmenu-gtk3 \
  libdbusmenu-qt5 \
  libdc1394 \
  libdca \
  libde265 \
  libdmapsharing \
  libdrm \
  libdv \
  libdvbpsi \
  libdvdnav \
  libdvdread \
  libe-book \
  libebml \
  libedit \
  libelf \
  libepoxy \
  libepubgen \
  libetonyek \
  libev \
  libevdev \
  libevent \
  libexif \
  libexttextcat \
  libfdk-aac \
  libffi \
  libfontenc \
  libfreeaptx \
  libfreehand \
  libftdi \
  libgcrypt \
  libgdata \
  libgdiplus \
  libgdm \
  libgee \
  libgexiv2 \
  libgit2 \
  libglade \
  libglvnd \
  libgme \
  libgnomekbd \
  libgpg-error \
  libgphoto2 \
  libgrss \
  libgsf \
  libgssglue \
  libgtop \
  libgudev \
  libgusb \
  libgweather \
  libgxps \
  libhandy \
  libhandy0 \
  libheif \
  libibus \
  libical \
  libice \
  libid3tag \
  libidn \
  libidn2 \
  libiec61883 \
  libieee1284 \
  libimagequant \
  libimobiledevice \
  libindicator-gtk3 \
  libinih \
  libinput \
  libinstpatch \
  libiptcdata \
  libixion \
  libjpeg-turbo \
  libkate \
  libksba \
  liblangtag \
  libldac \
  libldap \
  liblouis \
  liblqr \
  liblrdf \
  libluv \
  libmad \
  libmanette \
  libmatroska \
  libmaxminddb \
  libmd \
  libmediaart \
  libmfx \
  libmicrodns \
  libmicrohttpd \
  libmm-glib \
  libmms \
  libmng \
  libmnl \
  libmodplug \
  libmpc \
  libmpcdec \
  libmpeg2 \
  libmspub \
  libmtp \
  libmusicbrainz5 \
  libmwaw \
  libmypaint \
  libnautilus-extension \
  libndp \
  libnet \
  libnetfilter_conntrack \
  libnewt \
  libnfnetlink \
  libnfs \
  libnftnl \
  libnghttp2 \
  libnice \
  libnl \
  libnm \
  libnma \
  libnotify \
  libnsl \
  libnumbertext \
  liboauth \
  libodfgen \
  libofa \
  libogg \
  libomxil-bellagio \
  libopenaptx \
  liborcus \
  libosinfo \
  libp11-kit \
  libpagemaker \
  libpano13 \
  libpaper \
  libpcap \
  libpciaccess \
  libpeas \
  libpgm \
  libpipeline \
  libplacebo \
  libplist \
  libpng \
  libportal \
  libproxy \
  libpsl \
  libpulse \
  libpwquality \
  libquvi \
  libquvi-scripts \
  libqxp \
  libraqm \
  libraw \
  libraw1394 \
  libreoffice-still \
  libreoffice-still-en-gb \
  librevenge \
  librsvg \
  libsamplerate \
  libsasl \
  libseccomp \
  libsecp256k1 \
  libsecret \
  libshout \
  libsigc++ \
  libsm \
  libsndfile \
  libsodium \
  libsoup \
  libsoxr \
  libspectre \
  libspiro \
  libsrtp \
  libssh \
  libssh2 \
  libstaroffice \
  libstemmer \
  libsynctex \
  libtar \
  libtasn1 \
  libteam \
  libtermkey \
  libtg_owt \
  libthai \
  libtheora \
  libtiff \
  libtirpc \
  libtommath \
  libtool \
  libunistring \
  libunwind \
  libupnp \
  libusb \
  libusb-compat \
  libusbmuxd \
  libutempter \
  libuv \
  libva \
  libvdpau \
  libvips \
  libvisio \
  libvisual \
  libvorbis \
  libvpx \
  libvterm \
  libwacom \
  libwebp \
  libwmf \
  libwpd \
  libwpe \
  libwpg \
  libwps \
  libx11 \
  libxau \
  libxaw \
  libxcb \
  libxcomposite \
  libxcrypt \
  libxcursor \
  libxdamage \
  libxdg-basedir \
  libxdmcp \
  libxext \
  libxfixes \
  libxfont2 \
  libxft \
  libxi \
  libxinerama \
  libxkbcommon \
  libxkbcommon-x11 \
  libxkbfile \
  libxklavier \
  libxml2 \
  libxmu \
  libxpm \
  libxrandr \
  libxrender \
  libxshmfence \
  libxslt \
  libxss \
  libxt \
  libxtst \
  libxv \
  libxvmc \
  libxxf86vm \
  libyaml \
  libyuv \
  libzmf \
  licenses \
  lilv \
  linssid \
  linux \
  linux-api-headers \
  linux-firmware \
  linux-headers \
  lirc \
  llvm-libs \
  lm_sensors \
  lmdb \
  logrotate \
  lpsolve \
  lsof \
  lua \
  lua51 \
  lua52 \
  lua52-bitop \
  lua52-expat \
  lua52-lpeg \
  lua52-luajson \
  lua52-socket \
  lua53 \
  luajit \
  lvm2 \
  lxterminal \
  lynx \
  lz4 \
  lzo \
  m4 \
  mailcap \
  make \
  man-db \
  man-pages \
  masterpdfeditor-free \
  maven \
  mbedtls \
  md4c \
  mdadm \
  mesa \
  meson \
  metis \
  minizip \
  mjpegtools \
  mkinitcpio \
  mkinitcpio-busybox \
  mobile-broadband-provider-info \
  mod_dnssd \
  mono \
  mousetweaks \
  mpfr \
  mpg123 \
  mplayer \
  msgpack-c \
  mtdev \
  mutter \
  mypaint-brushes1 \
  myrepos \
  nano \
  nautilus \
  ncurses \
  ndctl \
  neomutt \
  neon \
  neovim \
  net-snmp \
  netctl \
  netpbm \
  nettle \
  network-manager-applet \
  networkmanager \
  networkmanager-openconnect \
  ninja \
  nm-connection-editor \
  notmuch \
  notmuch-runtime \
  noto-fonts \
  noto-fonts-emoji \
  npth \
  nspr \
  nss \
  ntp \
  obs-studio \
  oniguruma \
  openal \
  openconnect \
  opencore-amr \
  opencv \
  openexr \
  openjpeg2 \
  openmp \
  openmpi \
  openresolv \
  openssh \
  openssl \
  openvpn \
  opus \
  orc \
  osinfo-db \
  osm-gps-map \
  p11-kit \
  pacaur \
  pacman \
  pacman-mirrorlist \
  pahole \
  pam \
  pambase \
  pango \
  pangomm \
  parted \
  pass \
  patch \
  pavucontrol \
  pciutils \
  pcre \
  pcre2 \
  pcsclite \
  pdfmod \
  perl \
  perl-alien-build \
  perl-alien-libxml2 \
  perl-b-hooks-endofscope \
  perl-bit-vector \
  perl-bytes-random-secure \
  perl-capture-tiny \
  perl-carp-clan \
  perl-cgi \
  perl-class-data-inheritable \
  perl-class-inspector \
  perl-class-load \
  perl-class-singleton \
  perl-clone \
  perl-crypt-random-seed \
  perl-crypt-random-tesha2 \
  perl-crypt-ssleay \
  perl-data-optlist \
  perl-date-calc \
  perl-date-manip \
  perl-datetime \
  perl-datetime-format-strptime \
  perl-datetime-locale \
  perl-datetime-timezone \
  perl-dbi \
  perl-devel-stacktrace \
  perl-dist-checkconflicts \
  perl-encode-locale \
  perl-error \
  perl-eval-closure \
  perl-exception-class \
  perl-exporter-tiny \
  perl-ffi-checklib \
  perl-file-chdir \
  perl-file-listing \
  perl-file-sharedir \
  perl-file-sharedir-install \
  perl-file-which \
  perl-finance-quote \
  perl-html-element-extended \
  perl-html-parser \
  perl-html-tableextract \
  perl-html-tagset \
  perl-html-tree \
  perl-http-cookies \
  perl-http-daemon \
  perl-http-date \
  perl-http-message \
  perl-http-negotiate \
  perl-inc-latest \
  perl-io-html \
  perl-io-socket-ssl \
  perl-json \
  perl-json-parse \
  perl-libwww \
  perl-list-allutils \
  perl-list-moreutils \
  perl-list-moreutils-xs \
  perl-list-someutils \
  perl-list-utilsby \
  perl-lwp-mediatypes \
  perl-lwp-protocol-https \
  perl-mailtools \
  perl-math-random-isaac \
  perl-math-round \
  perl-mime-charset \
  perl-module-build \
  perl-module-implementation \
  perl-module-runtime \
  perl-mozilla-ca \
  perl-mro-compat \
  perl-namespace-autoclean \
  perl-namespace-clean \
  perl-net-http \
  perl-net-ssleay \
  perl-number-misc \
  perl-package-deprecationmanager \
  perl-package-stash \
  perl-package-stash-xs \
  perl-params-util \
  perl-params-validate \
  perl-params-validationcompiler \
  perl-path-class \
  perl-path-tiny \
  perl-role-tiny \
  perl-specio \
  perl-string-util \
  perl-sub-exporter \
  perl-sub-exporter-progressive \
  perl-sub-identify \
  perl-sub-install \
  perl-sub-name \
  perl-term-readkey \
  perl-test-fatal \
  perl-text-template \
  perl-timedate \
  perl-try-tiny \
  perl-unicode-linebreak \
  perl-uri \
  perl-variable-magic \
  perl-www-robotrules \
  perl-xml-libxml \
  perl-xml-namespacesupport \
  perl-xml-parser \
  perl-xml-sax \
  perl-xml-sax-base \
  perl-yaml-tiny \
  picom \
  pinentry \
  pipewire \
  pipewire-media-session \
  pixman \
  pkcs11-helper \
  pkgconf \
  playerctl \
  pnmixer \
  po4a \
  polkit \
  poppler \
  poppler-data \
  poppler-glib \
  popt \
  portaudio \
  powertop \
  procps-ng \
  procs \
  protobuf \
  psmisc \
  pugixml \
  pulseaudio \
  pulseaudio-alsa \
  pulseaudio-bluetooth \
  python \
  python-aiohttp \
  python-aiohttp-socks \
  python-aiorpcx \
  python-appdirs \
  python-asn1crypto \
  python-async-timeout \
  python-attrs \
  python-bcrypt \
  python-beautifulsoup4 \
  python-bitstring \
  python-cached-property \
  python-cairo \
  python-certifi \
  python-cffi \
  python-chardet \
  python-click \
  python-cryptography \
  python-decorator \
  python-distlib \
  python-distro \
  python-dnspython \
  python-docker \
  python-docker-pycreds \
  python-dockerpty \
  python-docopt \
  python-dotenv \
  python-ecdsa \
  python-filelock \
  python-flask \
  python-flask-cors \
  python-gobject \
  python-html5lib \
  python-idna \
  python-importlib-metadata \
  python-itsdangerous \
  python-jinja \
  python-jsonrpclib-pelix \
  python-jsonschema \
  python-markdown \
  python-markupsafe \
  python-more-itertools \
  python-msgpack \
  python-multidict \
  python-ordered-set \
  python-orjson \
  python-packaging \
  python-paramiko \
  python-pbkdf2 \
  python-pillow \
  python-ply \
  python-protobuf \
  python-pyaes \
  python-pyaudio \
  python-pycparser \
  python-pycryptodomex \
  python-pycups \
  python-pycurl \
  python-pydbus \
  python-pynacl \
  python-pyopenssl \
  python-pyparsing \
  python-pyqt5 \
  python-pyqt5-sip \
  python-pyqt5-webengine \
  python-pyrsistent \
  python-pysocks \
  python-qrcode \
  python-requests \
  python-resolvelib \
  python-send2trash \
  python-setuptools \
  python-six \
  python-soupsieve \
  python-texttable \
  python-toml \
  python-typing_extensions \
  python-urllib3 \
  python-waitress \
  python-webencodings \
  python-websocket-client \
  python-werkzeug \
  python-wheel \
  python-yaml \
  python-yarl \
  python-zipp \
  python2 \
  python2-appdirs \
  python2-bcrypt \
  python2-cairo \
  python2-cffi \
  python2-dateutil \
  python2-gobject \
  python2-ordered-set \
  python2-packaging \
  python2-ply \
  python2-pycparser \
  python2-pyparsing \
  python2-setuptools \
  python2-six \
  qpdf \
  qrencode \
  qt5-base \
  qt5-declarative \
  qt5-imageformats \
  qt5-location \
  qt5-multimedia \
  qt5-svg \
  qt5-tools \
  qt5-wayland \
  qt5-webchannel \
  qt5-webengine \
  qt5-x11extras \
  quazip \
  qwt \
  ranger \
  raptor \
  rasqal \
  rav1e \
  rdesktop \
  re2 \
  readline \
  recode \
  redland \
  redshift \
  reiserfsprogs \
  rest \
  rhash \
  ripgrep \
  rnnoise \
  rofi \
  roxterm \
  rsync \
  rtkit \
  rtmpdump \
  ruby \
  ruby-irb \
  ruby-reline \
  ruby2.7 \
  rubygems \
  run-parts \
  runc \
  rust-analyzer \
  rustup \
  s-nail \
  sakura \
  sane \
  sbc \
  sdl \
  sdl2 \
  seahorse \
  sed \
  serd \
  shaderc \
  shadow \
  shared-color-targets \
  shared-mime-info \
  signal-desktop \
  simple-scan \
  simplescreenrecorder \
  slang \
  smbclient \
  snappy \
  sord \
  sound-theme-freedesktop \
  soundtouch \
  spandsp \
  speedcrunch \
  speex \
  speexdsp \
  spirv-tools \
  sqlite \
  sqlitebrowser \
  sratom \
  srt \
  sshpass \
  startup-notification \
  stoken \
  stow \
  strace \
  sudo \
  suitesparse \
  sushi \
  svt-av1 \
  svt-hevc \
  syncthing \
  syncthing-gtk \
  sysfsutils \
  system-config-printer \
  systemd \
  systemd-boot-pacman-hook \
  systemd-libs \
  systemd-sysvcompat \
  t1lib \
  taglib \
  talloc \
  tamsyn-font \
  tar \
  tbb \
  tcl \
  tcpdump \
  tcptrace \
  tdb \
  telegram-desktop \
  tepl \
  terminus-font \
  tevent \
  texinfo \
  the_silver_searcher \
  thin-provisioning-tools \
  tig \
  tk \
  tlp \
  tmux \
  totem-pl-parser \
  traceroute \
  tracker \
  tracker-miners \
  tracker3 \
  tracker3-miners \
  tre \
  tree \
  tree-sitter \
  tslib \
  ttf-anonymous-pro \
  ttf-bitstream-vera \
  ttf-cascadia-code \
  ttf-comic-mono-git \
  ttf-croscore \
  ttf-dejavu \
  ttf-droid \
  ttf-fira-code \
  ttf-fira-mono \
  ttf-hack \
  ttf-ibm-plex \
  ttf-inconsolata \
  ttf-jetbrains-mono \
  ttf-joypixels \
  ttf-liberation \
  ttf-linux-libertine \
  ttf-opensans \
  ttf-roboto \
  ttf-ubuntu-font-family \
  twolame \
  typora \
  tzdata \
  uchardet \
  udisks2 \
  unibilium \
  unicode-character-database \
  unicode-emoji \
  universal-ctags-git \
  unrar \
  unzip \
  upower \
  usbmuxd \
  usbutils \
  util-linux \
  util-linux-libs \
  v4l-utils \
  vagrant \
  vi \
  vid.stab \
  vigra \
  virtualbox \
  virtualbox-host-modules-arch \
  vlc \
  vmaf \
  vokoscreen \
  volume_key \
  vpnc \
  vte-common \
  vte3 \
  vulkan-headers \
  vulkan-icd-loader \
  w3m \
  wavpack \
  wayland \
  wayland-protocols \
  webkit2gtk \
  webrtc-audio-processing \
  weechat \
  wget \
  which \
  whois \
  wildmidi \
  wireless_tools \
  wireshark-cli \
  wireshark-qt \
  woff2 \
  wpa_supplicant \
  wpebackend-fdo \
  wxgtk-common \
  wxgtk3 \
  x264 \
  x265 \
  xapian-core \
  xautolock \
  xbindkeys \
  xcb-proto \
  xcb-util \
  xcb-util-cursor \
  xcb-util-image \
  xcb-util-keysyms \
  xcb-util-renderutil \
  xcb-util-wm \
  xcb-util-xrm \
  xclip \
  xdg-dbus-proxy \
  xdg-utils \
  xdotool \
  xf86-input-libinput \
  xfsprogs \
  xh \
  xidlehook \
  xkeyboard-config \
  xkeycaps \
  xmlsec \
  xmlto \
  xorg-fonts-encodings \
  xorg-server \
  xorg-server-common \
  xorg-setxkbmap \
  xorg-xauth \
  xorg-xdpyinfo \
  xorg-xev \
  xorg-xhost \
  xorg-xinit \
  xorg-xkbcomp \
  xorg-xmodmap \
  xorg-xprop \
  xorg-xrandr \
  xorg-xrdb \
  xorg-xset \
  xorg-xwayland \
  xorg-xwininfo \
  xorgproto \
  xss-lock \
  xvidcore \
  xxhash \
  xz \
  yajl \
  yay \
  yelp \
  yelp-xsl \
  yubico-c \
  yubico-c-client \
  yubikey-personalization \
  zbar \
  zenity \
  zeromq \
  zimg \
  zip \
  zita-alsa-pcmi \
  zita-resampler \
  zlib \
  zoom \
  zsh \
  zstd \
  zvbi \
  zxing-cpp \
)





##
# Bootstrap specific tasks, not safe to be re-run/destructive
#

function bootstrap {
  if [ -f /mnt/.BOOTSTRAPPED ] || [ -f /.BOOTSTRAPPED ]
  then
    echo "This system appears to have been bootstrapped already,"
    echo " found an existing .BOOTSTRAPPED file, skipping."
    return
  fi

  echo "Updating mirror list"
  if [ ! -f /tmp/mirrorlist ]
  then
    echo 'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    pacman -Sy
    pacman -S --noconfirm pacman-contrib
    curl -sL "$MIRRORLIST_URL" | \
        sed -e 's/^#Server/Server/' | \
        rankmirrors --verbose -n 0 - \
        > /tmp/mirrorlist \
        && cp /tmp/mirrorlist /etc/pacman.d/
  fi

  echo "Updating keyring and installing dialog"
  pacman -Sy --noconfirm \
    archlinux-keyring \
    dialog

  ### Get infomation from user ###
  hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
  clear
  : ${hostname:?"hostname cannot be empty"}

  user=$(dialog --stdout --inputbox "Enter admin username" 0 0) || exit 1
  clear
  : ${user:?"user cannot be empty"}

  password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
  clear
  : ${password:?"password cannot be empty"}
  password2=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
  clear
  [[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )

  devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
  device=$(dialog --stdout --menu "Select installtion disk" 0 0 0 ${devicelist}) || exit 1
  clear

  ### Set up logging ###
  exec 1> >(tee "/tmp/bootstrap-stdout.log")
  exec 2> >(tee "/tmp/bootstrap-stderr.log")

  timedatectl set-ntp true

  parted --script "${device}" -- mklabel gpt \
    mkpart primary fat32 1049kB 538MiB \
    set 1 boot on \
    set 1 esp on \
    mkpart primary ext4 538MiB 100% \
    name 1 boot \
    name 2 luks

  # Simple globbing was not enough as on one device I needed to match /dev/mmcblk0p1 
  # but not /dev/mmcblk0boot1 while being able to match /dev/sda1 on other devices.
  part_boot="$(ls ${device}* | grep -E "^${device}p?1$")"
  part_root="$(ls ${device}* | grep -E "^${device}p?2$")"

  wipefs "${part_boot}"
  wipefs "${part_root}"

  echo -n "${password}" | cryptsetup --verbose --batch-mode luksFormat --type luks2 ${part_root} -
  echo -n "${password}" | cryptsetup --verbose --key-file - open ${part_root} storage

  pvcreate /dev/mapper/storage
  vgcreate ${hostname} /dev/mapper/storage
  lvcreate -L 8G ${hostname} -n swap
  lvcreate -l 90%FREE ${hostname} -n root

  mkfs.vfat -F32 "${part_boot}"
  mkswap "/dev/${hostname}/swap"
  mkfs.ext4 "/dev/${hostname}/root"

  swapon "/dev/${hostname}/swap"
  mount "/dev/${hostname}/root" /mnt
  mkdir /mnt/boot
  mount "${part_boot}" /mnt/boot

  pacstrap /mnt base base-devel linux linux-firmware git zsh
  genfstab -U /mnt >> /mnt/etc/fstab
  echo "${hostname}" > /mnt/etc/hostname

  sed -i 's/^MODULES=()/MODULES=(atkbd)/' /mnt/etc/mkinitcpio.conf
  sed -i 's/^HOOKS=.*/HOOKS=(base udev keyboard keymap consolefont autodetect modconf block encrypt lvm2 filesystems fsck)/' /mnt/etc/mkinitcpio.conf

  arch-chroot /mnt bootctl install

  cat <<EOF > /mnt/boot/loader/loader.conf
default arch
EOF

  cat <<EOF > /mnt/boot/loader/entries/arch.conf
title    Arch Linux
linux    /vmlinuz-linux
initrd   /intel-ucode.img
initrd   /initramfs-linux.img
options  cryptdevice=UUID=$(blkid -s UUID -o value ${part_root}):storage resume=UUID=$(blkid -s UUID -o value /dev/${hostname}/swap) root=/dev/${hostname}/root rw
EOF

  echo "LANG=en_GB.UTF-8" > /mnt/etc/locale.conf

  arch-chroot /mnt useradd -mU -s /usr/bin/zsh -G wheel,uucp,video,audio,storage,games,input "$user"
  arch-chroot /mnt chsh -s /usr/bin/zsh

  echo "$user:$password" | chpasswd --root /mnt
  echo "root:$password" | chpasswd --root /mnt

  # Disable the internal system bell
  echo "blacklist pcspkr" > /mnt/etc/modprobe.d/nobeep.conf

  ln -sf /usr/share/zoneinfo/Europe/Berlin /mnt/etc/localtime

  sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /mnt/etc/sudoers

  arch-chroot /mnt su ${user} bash -c '\
    git clone https://aur.archlinux.org/yay.git /tmp/yay \
    && cd /tmp/yay \
    && makepkg -si --noconfirm'

  touch /mnt/.BOOTSTRAPPED

  arch-chroot /mnt sudo -u cewood bash -c '\
    curl -sL https://goo.gl/HtC7Mf | bash -s post'
  
  sed -i 's/%wheel ALL=(ALL) NOPASSWD: ALL/# %wheel ALL=(ALL) NOPASSWD: ALL/' /mnt/etc/sudoers
  sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /mnt/etc/sudoers
}





##
# Any normal/post-bootstrap tasks to perform
#
function post {
  if [ ! -f /.BOOTSTRAPPED ]
  then
    echo "This system hasn't been bootstrapped already,"
    echo " no /.BOOTSTRAPPED file found, skipping."
    return
  fi

  ### Set up logging ###
  exec 1> >(tee "/tmp/post-stdout.log")
  exec 2> >(tee "/tmp/post-stderr.log")

  yay --noconfirm -S ${PACKAGE_LIST[*]}
}





##
# Run the things
#
case ${1:-post} in
bootstrap)
  bootstrap
  ;;
post)
  post
  ;;
esac
