#!/bin/bash
#
# WARNING: this script will destroy data on the selected disk.
#
# This script can be run by executing the following:
#   curl -sL https://goo.gl/HtC7Mf | bash -s bootstrap
#

set -eoux pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=AT&country=BE&country=DK&country=FR&country=DE&country=NL&country=SE&country=CH&protocol=https&use_mirror_status=on"
PACKAGE_LIST=(
  arandr \
  aspell-en \
  aurvote \
  autorandr \
  chromium \
  code \
  compton \
  cups \
  dkms \
  dmenu \
  docker \
  docker-compose \
  dropbox \
  dunst \
  e2fsprogs \
  efibootmgr \
  elinks \
  eog \
  evemu \
  evince \
  fasd \
  feh \
  ferm \
  figlet \
  file-roller \
  findutils \
  firefox \
  fzf \
  galculator \
  gawk \
  gcc \
  gcc-libs \
  gdm \
  gedit \
  geteltorito \
  gettext \
  gimp \
  git-crypt \
  glibc \
  gnome-calculator \
  gnome-control-center \
  gnome-disk-utility \
  gnome-font-viewer \
  gnome-keyring \
  gnome-power-manager \
  gnome-screenshot \
  gnome-session \
  gnome-settings-daemon \
  gnome-shell \
  gnome-shell-extensions \
  gnome-system-monitor \
  gnome-terminal \
  gnome-themes-extra \
  gnome-tweaks \
  gnome-user-docs \
  gnome-user-share \
  gnu-netcat \
  gnucash \
  google-chrome \
  gopass \
  gparted \
  gpg-crypter \
  grep \
  grilo-plugins \
  gthumb \
  gtk-vnc \
  gucharmap \
  gvfs-afc \
  gvfs-goa \
  gvfs-google \
  gvfs-gphoto2 \
  gvfs-mtp \
  gvfs-nfs \
  gvfs-smb \
  gzip \
  htop \
  i3-wm \
  i3status \
  inetutils \
  intel-ucode \
  iproute2 \
  iputils \
  ispell \
  iw \
  jdk8-openjdk \
  jfsutils \
  jpdftweak \
  jq \
  kbdlight \
  keepassxc \
  less \
  libreoffice-still-en-gb \
  libtool \
  licenses \
  linssid \
  linux \
  linux-headers \
  logrotate \
  lvm2 \
  lxterminal \
  m4 \
  make \
  man-db \
  man-pages \
  masterpdfeditor \
  maven \
  mdadm \
  mousetweaks \
  mplayer \
  mutter \
  myrepos \
  nano \
  nautilus \
  neovim \
  netctl \
  network-manager-applet \
  networkmanager \
  ntp \
  obs-studio \
  openssh \
  openvpn \
  pacaur \
  pacman \
  pass \
  patch \
  pavucontrol \
  pciutils \
  pdfmod \
  perl \
  perl-date-manip \
  perl-finance-quote \
  perl-term-readkey \
  pkgconf \
  playerctl \
  pnmixer \
  powertop \
  procps-ng \
  psmisc \
  pulseaudio \
  python-setuptools \
  redshift \
  reiserfsprogs \
  ripgrep \
  rofi \
  roxterm \
  rsync \
  s-nail \
  sakura \
  seahorse \
  sed \
  shadow \
  simplescreenrecorder \
  speedcrunch \
  sqlitebrowser \
  sshpass \
  stow \
  strace \
  sudo \
  sushi \
  sysfsutils \
  system-config-printer \
  systemd-boot-pacman-hook \
  systemd-sysvcompat \
  tar \
  tcpdump \
  texinfo \
  the_silver_searcher \
  tig \
  tk \
  tmux \
  totem \
  tree \
  unrar \
  usbutils \
  util-linux \
  vagrant \
  vi \
  virtualbox \
  virtualbox-host-modules-arch \
  vlc \
  volti \
  wavemon \
  weechat \
  wget \
  which \
  wireshark-gtk \
  wpa_supplicant \
  x264 \
  xclip \
  xdg-user-dirs-gtk \
  xdotool \
  xf86-video-intel \
  xfsprogs \
  xkeycaps \
  xorg-server \
  xorg-xbacklight \
  xorg-xev \
  xorg-xmodmap \
  yay \
  zsh \
)





##
# Bootstrap specific tasks, not safe to be re-run/destructive
#

function bootstrap {
  if [ -f /mnt/.BOOTSTRAPPED ] || [ -f /.BOOTSTRAPPED ]
  then
    echo "This system appears to have been bootstrapped already,"
    echo " found an existing .BOOTSTRAPPED file, skipping."
    return
  fi

  echo "Updating mirror list"
  if [ ! -f /tmp/mirrorlist ]
  then
    echo 'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    pacman -Sy
    pacman -S --noconfirm pacman-contrib
    curl -sL "$MIRRORLIST_URL" | \
        sed -e 's/^#Server/Server/' | \
        rankmirrors --verbose -n 0 - \
        > /tmp/mirrorlist \
        && cp /tmp/mirrorlist /etc/pacman.d/
  fi

  echo "Updating keyring and installing dialog"
  pacman -Sy --noconfirm \
    archlinux-keyring \
    dialog

  ### Get infomation from user ###
  hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
  clear
  : ${hostname:?"hostname cannot be empty"}

  user=$(dialog --stdout --inputbox "Enter admin username" 0 0) || exit 1
  clear
  : ${user:?"user cannot be empty"}

  password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
  clear
  : ${password:?"password cannot be empty"}
  password2=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
  clear
  [[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )

  devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
  device=$(dialog --stdout --menu "Select installtion disk" 0 0 0 ${devicelist}) || exit 1
  clear

  ### Set up logging ###
  exec 1> >(tee "/tmp/bootstrap-stdout.log")
  exec 2> >(tee "/tmp/bootstrap-stderr.log")

  timedatectl set-ntp true

  parted --script "${device}" -- mklabel gpt \
    mkpart primary fat32 1049kB 538MiB \
    set 1 boot on \
    set 1 esp on \
    mkpart primary ext4 538MiB 100% \
    name 1 boot \
    name 2 luks

  # Simple globbing was not enough as on one device I needed to match /dev/mmcblk0p1 
  # but not /dev/mmcblk0boot1 while being able to match /dev/sda1 on other devices.
  part_boot="$(ls ${device}* | grep -E "^${device}p?1$")"
  part_root="$(ls ${device}* | grep -E "^${device}p?2$")"

  wipefs "${part_boot}"
  wipefs "${part_root}"

  echo -n "${password}" | cryptsetup --verbose --batch-mode luksFormat --type luks2 ${part_root} -
  echo -n "${password}" | cryptsetup --verbose --key-file - open ${part_root} storage

  pvcreate /dev/mapper/storage
  vgcreate ${hostname} /dev/mapper/storage
  lvcreate -L 8G ${hostname} -n swap
  lvcreate -l 90%FREE ${hostname} -n root

  mkfs.vfat -F32 "${part_boot}"
  mkswap "/dev/${hostname}/swap"
  mkfs.ext4 "/dev/${hostname}/root"

  swapon "/dev/${hostname}/swap"
  mount "/dev/${hostname}/root" /mnt
  mkdir /mnt/boot
  mount "${part_boot}" /mnt/boot

  pacstrap /mnt base base-devel linux linux-firmware git zsh
  genfstab -U /mnt >> /mnt/etc/fstab
  echo "${hostname}" > /mnt/etc/hostname

  sed -i 's/^MODULES=()/MODULES=(atkbd)/' /mnt/etc/mkinitcpio.conf
  sed -i 's/^HOOKS=.*/HOOKS=(base udev keyboard keymap consolefont autodetect modconf block encrypt lvm2 filesystems fsck)/' /mnt/etc/mkinitcpio.conf

  arch-chroot /mnt bootctl install

  cat <<EOF > /mnt/boot/loader/loader.conf
default arch
EOF

  cat <<EOF > /mnt/boot/loader/entries/arch.conf
title    Arch Linux
linux    /vmlinuz-linux
initrd   /intel-ucode.img
initrd   /initramfs-linux.img
options  cryptdevice=UUID=$(blkid -s UUID -o value ${part_root}):storage resume=UUID=$(blkid -s UUID -o value /dev/${hostname}/swap) root=/dev/${hostname}/root rw
EOF

  echo "LANG=en_GB.UTF-8" > /mnt/etc/locale.conf

  arch-chroot /mnt useradd -mU -s /usr/bin/zsh -G wheel,uucp,video,audio,storage,games,input "$user"
  arch-chroot /mnt chsh -s /usr/bin/zsh

  echo "$user:$password" | chpasswd --root /mnt
  echo "root:$password" | chpasswd --root /mnt

  # Disable the internal system bell
  echo "blacklist pcspkr" > /mnt/etc/modprobe.d/nobeep.conf

  ln -sf /usr/share/zoneinfo/Europe/Berlin /mnt/etc/localtime

  sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /mnt/etc/sudoers

  arch-chroot /mnt su ${user} bash -c '\
    git clone https://aur.archlinux.org/yay.git /tmp/yay \
    && cd /tmp/yay \
    && makepkg -si --noconfirm'

  cp $0 /mnt/bootstrap-arch
  
  sed -i 's/%wheel ALL=(ALL) NOPASSWD: ALL/# %wheel ALL=(ALL) NOPASSWD: ALL/' /mnt/etc/sudoers
  sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /mnt/etc/sudoers

  touch /mnt/.BOOTSTRAPPED
}





##
# Any normal/post-bootstrap tasks to perform
#
function post {
  if [ ! -f /.BOOTSTRAPPED ]
  then
    echo "This system hasn't been bootstrapped already,"
    echo " no /.BOOTSTRAPPED file found, skipping."
    return
  fi

  ### Set up logging ###
  exec 1> >(tee "/tmp/post-stdout.log")
  exec 2> >(tee "/tmp/post-stderr.log")

  for PACKAGE in "${PACKAGE_LIST[@]}"; do
    yay --noconfirm -S ${PACKAGE}
  done
}





##
# Run the things
#
case ${1:-post} in
bootstrap)
  bootstrap
  ;;
post)
  post
  ;;
chroot)
  arch-chroot /mnt sudo -u $user bash
  ;;
esac
